name: OMF Integration Tests

on: push
        
jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        continue-on-error: true
        run: |
          brew link python@3.8
          which python3
          python3 --version
          which python
          # python3 install.py
          pip3 install -r requirements.txt
      - name: Run tests
        continue-on-error: true
        run: |
          python3 test.py
  Windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        continue-on-error: true
        run: |
          choco install python --no-progress --version 3.6.8
          # python install.py
          which python
          pip install -r requirements.txt
      - name: Run tests
        continue-on-error: true
        run: |
          python test.py
